// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-1NRsBilqHrM-rLrIKuivzN4Jt1rMiwY',
    appId: '1:149350324741:web:f77e75e6ed4debec2e5a6c',
    messagingSenderId: '149350324741',
    projectId: 'readswap37',
    authDomain: 'readswap37.firebaseapp.com',
    storageBucket: 'readswap37.appspot.com',
    measurementId: 'G-Y0HTQH8ZTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvEk5LdzBDpHWk5hlrncOlCS9HiAKOk3E',
    appId: '1:149350324741:android:56e35b34729a19ce2e5a6c',
    messagingSenderId: '149350324741',
    projectId: 'readswap37',
    storageBucket: 'readswap37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzm_BwoaBGBkBEJNtEiQxPOWfX15r_F1I',
    appId: '1:149350324741:ios:147bfd7c4045cfdf2e5a6c',
    messagingSenderId: '149350324741',
    projectId: 'readswap37',
    storageBucket: 'readswap37.appspot.com',
    iosBundleId: 'com.example.readswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzm_BwoaBGBkBEJNtEiQxPOWfX15r_F1I',
    appId: '1:149350324741:ios:9ab0cf0b5d4471c12e5a6c',
    messagingSenderId: '149350324741',
    projectId: 'readswap37',
    storageBucket: 'readswap37.appspot.com',
    iosBundleId: 'example.readswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-1NRsBilqHrM-rLrIKuivzN4Jt1rMiwY',
    appId: '1:149350324741:web:d2261c85eb7110b62e5a6c',
    messagingSenderId: '149350324741',
    projectId: 'readswap37',
    authDomain: 'readswap37.firebaseapp.com',
    storageBucket: 'readswap37.appspot.com',
    measurementId: 'G-Q0HRDZGLMY',
  );
}
